// Copies the agent's domain types into the frontend so both packages share one
// definition without a build step. Run after editing agent/src/domain/types.ts.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "agent", "src", "domain", "types.ts");
const dst = join(root, "frontend", "lib", "domain.ts");
const body = readFileSync(src, "utf8");
writeFileSync(dst, `// GENERATED by scripts/sync-types.mjs from agent/src/domain/types.ts. Do not edit.\n${body}`);
console.log(`synced ${src} → ${dst}`);
