// GENERATED by scripts/sync-types.mjs from agent/src/domain/types.ts. Do not edit.
/**
 * RPG Fuel Platform — domain types.
 *
 * Mirrored verbatim in frontend/lib/domain.ts (run `npm run sync-types` at the
 * repo root after editing). Money is in dollars with up to 5 decimals for
 * per-gallon prices; gallons are plain numbers; timestamps are ISO strings.
 */

// ---------------------------------------------------------------------------
// Reference data
// ---------------------------------------------------------------------------

export type StaffRole = "admin" | "management" | "dispatch" | "pricing" | "billing";

export interface StaffUser {
  id: string;
  name: string;
  email: string;
  role: StaffRole;
}

export type BillingBasis = "net" | "gross";
export type CustomerStatus = "active" | "on_hold" | "inactive";

export interface Customer {
  id: string;
  code: string;
  name: string;
  industry: string;
  billingBasis: BillingBasis;
  paymentTermsDays: number;
  creditLimit: number;
  taxExempt: boolean;
  status: CustomerStatus;
  /** Opaque token that scopes the customer portal (MVP stand-in for portal auth). */
  portalToken: string;
  quickbooksCustomerId?: string;
  notes?: string;
}

export interface DeliveryLocation {
  id: string;
  customerId: string;
  name: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  deliveryInstructions?: string;
}

export interface Contact {
  id: string;
  customerId: string;
  name: string;
  title: string;
  email: string;
  phone?: string;
  role: "ordering" | "billing" | "receiving";
}

export type ProductCategory = "diesel" | "gasoline" | "ethanol_blend" | "def";
export type TaxCategory = "clear_diesel" | "dyed_diesel" | "gasoline" | "def";

export interface Product {
  id: string;
  code: string;
  name: string;
  category: ProductCategory;
  dyed: boolean;
  taxCategory: TaxCategory;
}

export interface Supplier {
  id: string;
  code: string;
  name: string;
  bolSource: "feed" | "email" | "manual";
}

export interface Terminal {
  id: string;
  code: string;
  name: string;
  city: string;
  state: string;
  supplierIds: string[];
}

export interface Carrier {
  id: string;
  code: string;
  name: string;
  /** Fallback freight rate when no lane rate matches. */
  defaultRatePerGallon: number;
}

export interface CarrierRate {
  id: string;
  carrierId: string;
  terminalId: string;
  destinationState: string;
  ratePerGallon: number;
  minimumCharge: number;
}

// ---------------------------------------------------------------------------
// Pricing and market
// ---------------------------------------------------------------------------

export interface PriceIndex {
  id: string;
  code: string;
  name: string;
  source: string;
  productId?: string;
}

export interface IndexPrice {
  id: string;
  indexId: string;
  /** ISO date (yyyy-mm-dd). */
  date: string;
  value: number;
  change: number;
}

export interface RackPrice {
  id: string;
  terminalId: string;
  supplierId: string;
  productId: string;
  /** Rack postings change at a specific time; keep the full timestamp. */
  effectiveAt: string;
  pricePerGallon: number;
  source: "manual" | "import" | "feed";
  enteredBy?: string;
}

export type BasisType = "rack" | "index" | "fixed";
export type TaxTreatment = "taxable" | "exempt";

export interface PricingRule {
  id: string;
  name: string;
  /** null = applies to every customer (default rule). */
  customerId: string | null;
  productId: string;
  terminalId: string | null;
  deliveryLocationId: string | null;
  basisType: BasisType;
  /** terminalId for rack, indexId for index; unused for fixed. */
  basisRef: string | null;
  fixedPrice: number | null;
  differential: number;
  freightPerGallon: number;
  feesPerGallon: number;
  taxTreatment: TaxTreatment;
  effectiveStart: string;
  effectiveEnd: string | null;
  priority: number;
  status: "active" | "draft" | "expired";
}

export interface CustomerPrice {
  id: string;
  customerId: string;
  productId: string;
  terminalId: string;
  deliveryLocationId: string | null;
  priceDate: string;
  computedAt: string;
  pricingRuleId: string;
  basisType: BasisType;
  basisValue: number;
  differential: number;
  freight: number;
  fees: number;
  taxesPerGallon: number;
  sellPricePerGallon: number;
  explanation: string[];
}

export type Direction = "up" | "down" | "flat";

export interface Forecast {
  id: string;
  indexId: string;
  targetDate: string;
  direction: Direction;
  confidence: number;
  modelVersion: string;
  rationale: string;
  realizedDirection?: Direction;
}

// ---------------------------------------------------------------------------
// Orders and intake
// ---------------------------------------------------------------------------

export type OrderStatus =
  | "received"
  | "confirmed"
  | "carrier_confirmed"
  | "in_transit"
  | "delivered"
  | "cancelled";

export const ORDER_STATUSES: OrderStatus[] = [
  "received",
  "confirmed",
  "carrier_confirmed",
  "in_transit",
  "delivered",
  "cancelled",
];

export interface Order {
  id: string;
  orderNumber: string;
  customerId: string;
  deliveryLocationId: string;
  productId: string;
  requestedGallons: number;
  /** ISO date. */
  requestedDate: string;
  requestedWindow?: string;
  customerPo?: string;
  specialInstructions?: string;
  source: "email" | "manual" | "portal";
  emailIntakeId?: string;
  status: OrderStatus;
  creditHold: boolean;
  createdAt: string;
}

export interface OrderStatusEvent {
  id: string;
  orderId: string;
  from: OrderStatus | null;
  to: OrderStatus;
  occurredAt: string;
  actorId: string;
  note?: string;
}

export interface ParsedOrder {
  customerId?: string;
  customerName?: string;
  deliveryLocationId?: string;
  deliveryLocationName?: string;
  productId?: string;
  productName?: string;
  gallons?: number;
  requestedDate?: string;
  customerPo?: string;
  specialInstructions?: string;
  /** 0..1 per extracted field. */
  fieldConfidence: Record<string, number>;
}

export type IntakeReviewStatus = "pending" | "approved" | "rejected" | "duplicate";

export interface EmailIntake {
  id: string;
  messageId: string;
  receivedAt: string;
  from: string;
  subject: string;
  body: string;
  parsed: ParsedOrder;
  /** Overall confidence 0..1. */
  confidence: number;
  issues: string[];
  reviewStatus: IntakeReviewStatus;
  reviewedBy?: string;
  reviewedAt?: string;
  orderId?: string;
}

// ---------------------------------------------------------------------------
// Loads, BOLs, deliveries
// ---------------------------------------------------------------------------

export type LoadStatus =
  | "planned"
  | "dispatched"
  | "loading"
  | "in_transit"
  | "delivered"
  | "closed";

export const LOAD_STATUSES: LoadStatus[] = [
  "planned",
  "dispatched",
  "loading",
  "in_transit",
  "delivered",
  "closed",
];

export type BillingStatus =
  | "bol_received"
  | "pricing_verified"
  | "ready_to_invoice"
  | "invoiced"
  | "paid";

export const BILLING_STATUSES: BillingStatus[] = [
  "bol_received",
  "pricing_verified",
  "ready_to_invoice",
  "invoiced",
  "paid",
];

export interface Load {
  id: string;
  loadNumber: string;
  orderIds: string[];
  customerId: string;
  deliveryLocationId: string;
  productId: string;
  carrierId: string;
  driverName?: string;
  terminalId: string;
  supplierId: string;
  plannedGallons: number;
  scheduledPickupAt: string;
  scheduledDeliveryAt: string;
  status: LoadStatus;
  /** Null until a BOL is attached (Module F workflow starts at BOL Received). */
  billingStatus: BillingStatus | null;
  bolId?: string;
  invoiceId?: string;
  /** Actual or expected freight cost for the whole load. */
  freightCost: number;
}

export interface LoadStatusEvent {
  id: string;
  loadId: string;
  from: LoadStatus | null;
  to: LoadStatus;
  occurredAt: string;
  actorId: string;
  note?: string;
}

export interface BolLine {
  productId: string;
  grossGallons: number;
  netGallons: number;
  supplierCostPerGallon: number;
  taxesPerGallon: number;
  feesPerGallon: number;
}

export type BolMatchStatus = "unmatched" | "matched" | "duplicate";

export interface Bol {
  id: string;
  bolNumber: string;
  supplierId: string;
  terminalId: string;
  carrierId: string;
  loadId: string | null;
  liftedAt: string;
  destinationText: string;
  customerRef: string;
  source: "feed" | "email" | "manual";
  dedupeHash: string;
  matchStatus: BolMatchStatus;
  lines: BolLine[];
}

export interface Delivery {
  id: string;
  loadId: string;
  deliveredAt: string;
  deliveredGallons: number;
  receiverName: string;
  ticketNumber: string;
}

// ---------------------------------------------------------------------------
// Billing
// ---------------------------------------------------------------------------

export type TaxComponent =
  | "federal_excise"
  | "state_excise"
  | "environmental"
  | "lust";

export interface TaxRate {
  id: string;
  state: string;
  taxCategory: TaxCategory;
  component: TaxComponent;
  ratePerGallon: number;
  effectiveStart: string;
  effectiveEnd: string | null;
}

export interface TaxLine {
  component: TaxComponent;
  ratePerGallon: number;
  amount: number;
}

export interface InvoiceLine {
  id: string;
  bolId: string;
  productId: string;
  billedGallons: number;
  basis: BillingBasis;
  pricePerGallon: number;
  customerPriceId?: string;
  freight: number;
  fees: number;
  taxes: TaxLine[];
  lineTotal: number;
}

export type InvoiceStatus =
  | "draft"
  | "pending_approval"
  | "approved"
  | "synced"
  | "paid"
  | "void";

export interface Invoice {
  id: string;
  invoiceNumber: string;
  customerId: string;
  loadId: string;
  status: InvoiceStatus;
  issueDate: string;
  dueDate: string;
  lines: InvoiceLine[];
  subtotal: number;
  taxTotal: number;
  freightTotal: number;
  feesTotal: number;
  total: number;
  quickbooksInvoiceId?: string;
  syncedAt?: string;
  approvedBy?: string;
  approvedAt?: string;
  rejectionReason?: string;
  createdAt: string;
}

export interface Payment {
  id: string;
  invoiceId: string;
  quickbooksPaymentId: string;
  amount: number;
  receivedAt: string;
  method: string;
}

/** Record in the mock QuickBooks ledger (stands in for the external system). */
export interface QbInvoice {
  id: string;
  invoiceId: string;
  docNumber: string;
  customerRef: string;
  totalAmt: number;
  balance: number;
  txnDate: string;
  status: "open" | "paid";
}

// ---------------------------------------------------------------------------
// Profitability and controls
// ---------------------------------------------------------------------------

export interface LoadMargin {
  /** Same as loadId; one margin row per load. */
  id: string;
  loadId: string;
  customerId: string;
  productId: string;
  gallons: number;
  revenue: number;
  supplierCost: number;
  taxesPassthrough: number;
  freightCost: number;
  expectedGrossProfit: number;
  actualGrossProfit: number | null;
  profitPerGallon: number | null;
  variance: number | null;
  computedAt: string;
}

/** Reporting period for the day / week / month rollups (Module B). */
export type RollupPeriod = "day" | "week" | "month";

/** Delivered volume, revenue, and gross profit for one calendar bucket. */
export interface PeriodRollup {
  period: RollupPeriod;
  /** Bucket id: yyyy-mm-dd, yyyy-Www (ISO week, Monday start), or yyyy-mm. */
  key: string;
  label: string;
  /** Inclusive calendar bounds (yyyy-mm-dd). */
  start: string;
  end: string;
  loads: number;
  /** Delivered loads whose actual margin is still pending a BOL. */
  pendingLoads: number;
  gallons: number;
  revenue: number;
  supplierCost: number;
  freightCost: number;
  expectedGrossProfit: number;
  actualGrossProfit: number;
  /** Actual gross profit per gallon over the loads that have an actual margin. */
  profitPerGallon: number | null;
  /** Actual minus expected gross profit for the loads that have an actual margin. */
  variance: number;
}

export type ExceptionType =
  | "missing_bol"
  | "unassigned_customer"
  | "pricing_missing"
  | "pricing_mismatch"
  | "duplicate_bol"
  | "uninvoiced_load"
  | "low_margin"
  | "loss_load"
  | "credit_hold"
  | "stale_index";

export type Severity = "info" | "warning" | "critical";

export interface OpsException {
  id: string;
  type: ExceptionType;
  severity: Severity;
  entityType: "load" | "bol" | "order" | "invoice" | "customer" | "index";
  entityId: string;
  message: string;
  detectedAt: string;
  status: "open" | "acknowledged" | "resolved";
  resolvedBy?: string;
  resolvedAt?: string;
  resolutionNote?: string;
}

export interface AuditLogEntry {
  id: string;
  actorId: string;
  action: string;
  entityType: string;
  entityId: string;
  detail: string;
  occurredAt: string;
}

export type IntegrationKind =
  | "email_intake"
  | "bol_feed"
  | "index_feed"
  | "quickbooks_invoices"
  | "quickbooks_payments"
  | "forecast";

export interface IntegrationRun {
  id: string;
  kind: IntegrationKind;
  startedAt: string;
  finishedAt: string;
  status: "success" | "partial" | "failed";
  recordsIn: number;
  recordsOut: number;
  summary: string;
}

// ---------------------------------------------------------------------------
// Snapshot pushed to the UI (STATE_SNAPSHOT) and served by GET /ops
// ---------------------------------------------------------------------------

export interface OpsState {
  staff: StaffUser[];
  customers: Customer[];
  deliveryLocations: DeliveryLocation[];
  contacts: Contact[];
  products: Product[];
  suppliers: Supplier[];
  terminals: Terminal[];
  carriers: Carrier[];
  carrierRates: CarrierRate[];
  priceIndexes: PriceIndex[];
  indexPrices: IndexPrice[];
  rackPrices: RackPrice[];
  pricingRules: PricingRule[];
  customerPrices: CustomerPrice[];
  forecasts: Forecast[];
  emailIntakes: EmailIntake[];
  orders: Order[];
  orderEvents: OrderStatusEvent[];
  loads: Load[];
  loadEvents: LoadStatusEvent[];
  bols: Bol[];
  deliveries: Delivery[];
  taxRates: TaxRate[];
  invoices: Invoice[];
  payments: Payment[];
  qbInvoices: QbInvoice[];
  loadMargins: LoadMargin[];
  exceptions: OpsException[];
  auditLog: AuditLogEntry[];
  integrationRuns: IntegrationRun[];
}

export const COLLECTIONS = [
  "staff",
  "customers",
  "deliveryLocations",
  "contacts",
  "products",
  "suppliers",
  "terminals",
  "carriers",
  "carrierRates",
  "priceIndexes",
  "indexPrices",
  "rackPrices",
  "pricingRules",
  "customerPrices",
  "forecasts",
  "emailIntakes",
  "orders",
  "orderEvents",
  "loads",
  "loadEvents",
  "bols",
  "deliveries",
  "taxRates",
  "invoices",
  "payments",
  "qbInvoices",
  "loadMargins",
  "exceptions",
  "auditLog",
  "integrationRuns",
] as const;

export type Collection = (typeof COLLECTIONS)[number];

/** Human labels for workflow statuses (shared by UI and copilot cards). */
export const ORDER_STATUS_LABEL: Record<OrderStatus, string> = {
  received: "Order Received",
  confirmed: "Order Confirmed",
  carrier_confirmed: "Carrier Confirmed",
  in_transit: "Loading / In Transit",
  delivered: "Delivered",
  cancelled: "Cancelled",
};

export const BILLING_STATUS_LABEL: Record<BillingStatus, string> = {
  bol_received: "BOL Received",
  pricing_verified: "Pricing Verified",
  ready_to_invoice: "Ready to Invoice",
  invoiced: "Invoiced",
  paid: "Paid",
};

export const LOAD_STATUS_LABEL: Record<LoadStatus, string> = {
  planned: "Planned",
  dispatched: "Dispatched",
  loading: "Loading",
  in_transit: "In Transit",
  delivered: "Delivered",
  closed: "Closed",
};
